export const $ = (q) => document.querySelector(q);

export const UI = {
  id: $("#yourPeerId"),
  pid: $("#peerIdInput"),
  msg: $("#messageInput"),
  mic: $("#micCheckbox"),
  micLabel: $("#micLabel"),
  camera: $("#cameraCheckbox"),
  cameraLabel: $("#cameraLabel"),
  cameraOptions: $("#cameraOptions"),
  cameraSelect: $("#cameraSelect"),
  localVideo: $("#localVideo"),
  localVideoContainer: $("#localVideoContainer"),
  screen: $("#screenCheckbox"),
  screenLabel: $("#screenLabel"),
  screenVideo: $("#screenVideo"),
  screenContainer: $("#screenContainer"),
  ai: $("#aiCheckbox"),
  tChk: $("#translateCheckbox"),
  tLbl: $("#translateLabel"),
  tBox: $("#translation"),
  load: $("#loadingIndicator"),
  loading: $("#loadingIndicator"),
  sendBtn: $("#sendButton"),
  addBtn: $("#addUserBtn"),
  shareBtn: $("#shareBtn"),
  uList: $("#userList"),
  msgs: $("#receivedMessages"),
  audio: $("#remoteAudio"),

  // File transfer elements
  fileInput: $("#fileInput"),
  selectFileBtn: $("#selectFileBtn"),
  fileInfo: $("#fileInfo"),
  fileName: $("#fileName"),
  fileSize: $("#fileSize"),
  sendFileBtn: $("#sendFileBtn"),
  cancelFileBtn: $("#cancelFileBtn"),

  // Incoming file elements
  incomingFileContainer: $("#incomingFileContainer"),
  incomingFileName: $("#incomingFileName"),
  incomingFileSize: $("#incomingFileSize"),
  incomingFileProgress: $("#incomingFileProgress"),
  incomingFileProgressBar: $("#incomingFileProgressBar"),
  acceptFileBtn: $("#acceptFileBtn"),
  rejectFileBtn: $("#rejectFileBtn"),

  // Outgoing file elements
  outgoingFileContainer: $("#outgoingFileContainer"),
  outgoingFileName: $("#outgoingFileName"),
  outgoingFileSize: $("#outgoingFileSize"),
  outgoingFileProgress: $("#outgoingFileProgress"),
  outgoingFileProgressBar: $("#outgoingFileProgressBar"),
};
