export const $ = (q) => document.querySelector(q);

export const UI = {
  id: $("#yourPeerId"),
  pid: $("#peerIdInput"),
  msg: $("#messageInput"),
  mic: $("#micCheckbox"),
  micLabel: $("#micLabel"),
  camera: $("#cameraCheckbox"),
  cameraLabel: $("#cameraLabel"),
  cameraOptions: $("#cameraOptions"),
  cameraSelect: $("#cameraSelect"),
  localVideo: $("#localVideo"),
  localVideoContainer: $("#localVideoContainer"),
  screen: $("#screenCheckbox"),
  screenLabel: $("#screenLabel"),
  screenVideo: $("#screenVideo"),
  screenContainer: $("#screenContainer"),
  ai: $("#aiCheckbox"),
  tChk: $("#translateCheckbox"),
  tLbl: $("#translateLabel"),
  tBox: $("#translation"),
  load: $("#loadingIndicator"),
  loading: $("#loadingIndicator"),
  sendBtn: $("#sendButton"),
  addBtn: $("#addUserBtn"),
  uList: $("#userList"),
  msgs: $("#receivedMessages"),
  audio: $("#remoteAudio"),
};
